-- MystiCartes V2: set de lancement officiel (150 cartes) et Jeton Sylve.
-- Généré depuis docs/mysticartes_v2_card_catalog.md.

do $$
declare
  v_set_id uuid;
begin
  insert into public.card_sets (
    code, name, description, is_active, released_at
  ) values (
    'MCV2-LAUNCH',
    'MystiCartes V2 — Set de lancement',
    'Set officiel de lancement V2 : 150 cartes, 15 par famille principale.',
    true,
    null
  )
  on conflict (code) do update set
    name = excluded.name,
    description = excluded.description,
    is_active = excluded.is_active,
    released_at = excluded.released_at
  returning id into v_set_id;

  insert into public.cards (
    set_id, code, name, category, subtype, relic_mode, rarity,
    rank, atk, def, attribute, primary_family, secondary_families,
    mythic_summon_condition, effect_text, effect_key, effect_data,
    lore_text, art_url, is_active, sort_order, revision
  ) values
    (v_set_id, 'BAB-001', 'Apprenti du Gbaka', 'personnage', null, null, 'commune', 2, 900, 1200, 'vent', 'babi', '{}'::text[], null, 'À son invocation : tu peux piocher 1 carte, puis défausse 1 carte.', 'bab_001_apprenti_du_gbaka', '{}'::jsonb, null, null, true, 1, 1),
    (v_set_id, 'BAB-002', 'Messagère Wôrô-Wôrô', 'personnage', null, null, 'commune', 3, 1400, 1000, 'vent', 'babi', array['maquis']::text[], null, 'À son invocation : tu peux changer la position de combat d''un autre Personnage que tu contrôles.', 'bab_002_messagere_woro_woro', '{}'::jsonb, null, null, true, 2, 1),
    (v_set_id, 'BAB-003', 'Gardien du Carrefour', 'personnage', null, null, 'commune', 4, 1800, 1700, 'terre', 'babi', '{}'::text[], null, 'Aucun effet.', 'bab_003_gardien_du_carrefour', '{}'::jsonb, null, null, true, 3, 1),
    (v_set_id, 'BAB-004', 'Danseuse des Néons', 'personnage', null, null, 'rare', 4, 1700, 1500, 'lumière', 'babi', array['maquis']::text[], null, 'Une fois par tour, après l''activation d''une Action rapide : cette carte gagne 300 ATK jusqu''à la fin du tour.', 'bab_004_danseuse_des_neons', '{}'::jsonb, null, null, true, 4, 1),
    (v_set_id, 'BAB-005', 'Hacker du Marché', 'personnage', null, null, 'rare', 5, 2100, 1800, 'ombre', 'babi', '{}'::text[], null, 'À son invocation : cible 1 carte posée dans une Zone Action/Piège adverse ; regarde-la. Tu peux la renvoyer dans la main de son propriétaire.', 'bab_005_hacker_du_marche', '{}'::jsonb, null, null, true, 5, 1),
    (v_set_id, 'BAB-006', 'Champion du Bitume', 'personnage', null, null, 'épique', 6, 2400, 2000, 'feu', 'babi', array['savane']::text[], null, 'Une fois par tour, si cette carte détruit un Personnage au combat : pioche 1 carte, puis défausse 1 carte.', 'bab_006_champion_du_bitume', '{}'::jsonb, null, null, true, 6, 1),
    (v_set_id, 'BAB-007', 'Reine du Plateau', 'personnage', null, null, 'épique', 7, 2700, 2500, 'lumière', 'babi', array['royaume']::text[], null, 'Une fois par tour : tu peux renvoyer 1 autre carte Babi que tu contrôles dans ta main ; cette carte peut attaquer directement ce tour, mais les dégâts de cette attaque sont divisés par deux, arrondis au supérieur.', 'bab_007_reine_du_plateau', '{}'::jsonb, null, null, true, 7, 1),
    (v_set_id, 'BAB-008', 'Trajet Express', 'action', 'quick', null, 'commune', null, null, null, 'vent', 'babi', '{}'::text[], null, 'Cible 1 Personnage Babi que tu contrôles ; change sa position de combat. S''il passe en Attaque, il gagne 300 ATK ce tour.', 'bab_008_trajet_express', '{}'::jsonb, null, null, true, 8, 1),
    (v_set_id, 'BAB-009', 'Réseau Saturé', 'action', 'normal', null, 'rare', null, null, null, 'ombre', 'babi', '{}'::text[], null, 'Cible 1 carte posée dans une Zone Action/Piège adverse ; renvoie-la dans la main de son propriétaire.', 'bab_009_reseau_sature', '{}'::jsonb, null, null, true, 9, 1),
    (v_set_id, 'BAB-010', 'Battement de la Ville', 'action', 'normal', null, 'épique', null, null, null, 'lumière', 'babi', array['ancêtre']::text[], null, 'Invocation Fusion : envoie depuis ton terrain au Cimetière « Messagère Wôrô-Wôrô » et « Champion du Bitume » ; invoque spécialement « Génie d''Abidjan, Cœur Électrique » depuis ta Réserve des Mythiques.', 'bab_010_battement_de_la_ville', '{}'::jsonb, null, null, true, 10, 1),
    (v_set_id, 'BAB-011', 'Feu Rouge Mystique', 'piège', 'normal', null, 'commune', null, null, null, 'feu', 'babi', '{}'::text[], null, 'Lorsqu''un Personnage adverse déclare une attaque : annule cette attaque, puis passe l''attaquant en Défense s''il peut changer de position.', 'bab_011_feu_rouge_mystique', '{}'::jsonb, null, null, true, 11, 1),
    (v_set_id, 'BAB-012', 'Coupure de Courant', 'piège', 'counter', null, 'rare', null, null, null, 'ombre', 'babi', '{}'::text[], null, 'Lorsqu''une Action est activée : défausse 1 carte ; annule l''activation et détruis cette Action.', 'bab_012_coupure_de_courant', '{}'::jsonb, null, null, true, 12, 1),
    (v_set_id, 'BAB-013', 'Abidjan Minuit', 'terrain', null, null, 'rare', null, null, null, 'lumière', 'babi', array['maquis']::text[], null, 'Tous les Personnages Babi gagnent 200 ATK/DEF. La première Action rapide que tu actives pendant chaque tour ne peut pas être annulée par une Vitesse 2.', 'bab_013_abidjan_minuit', '{}'::jsonb, null, null, true, 13, 1),
    (v_set_id, 'BAB-014', 'Smartphone des Ancêtres', 'relique', null, 'equipment', 'épique', null, null, null, 'esprit', 'babi', array['ancêtre']::text[], null, 'Équipe uniquement un Personnage Babi. Une fois par tour : regarde la carte du dessus de ton deck ; laisse-la au-dessus ou place-la sous le deck.', 'bab_014_smartphone_des_ancetres', '{}'::jsonb, null, null, true, 14, 1),
    (v_set_id, 'BAB-015', 'Génie d''Abidjan, Cœur Électrique', 'mythique', null, null, 'légendaire', 9, 3200, 2800, 'lumière', 'babi', array['ancêtre']::text[], '{"method":"fusion","trigger_card_code":"BAB-010","source":"field","destination":"graveyard","materials":[{"card_code":"BAB-002","quantity":1},{"card_code":"BAB-006","quantity":1}]}'::jsonb, 'Doit d''abord être invoqué par « Battement de la Ville ». À son invocation : renvoie jusqu''à 2 cartes posées adverses dans la main de leur propriétaire. Une fois par tour, lorsqu''une Action rapide est activée : cette carte gagne 500 ATK jusqu''à la fin du tour.', 'bab_015_genie_d_abidjan_coeur_electrique', '{}'::jsonb, null, null, true, 15, 1),
    (v_set_id, 'ROY-001', 'Page aux Bracelets d''Or', 'personnage', null, null, 'commune', 1, 400, 1000, 'lumière', 'royaume', array['village']::text[], null, 'Si cette carte est sacrifiée pour l''invocation d''un Personnage Royaume : pioche 1 carte.', 'roy_001_page_aux_bracelets_d_or', '{}'::jsonb, null, null, true, 16, 1),
    (v_set_id, 'ROY-002', 'Lancière de la Porte Rouge', 'personnage', null, null, 'commune', 3, 1500, 1200, 'feu', 'royaume', '{}'::text[], null, 'Aucun effet.', 'roy_002_lanciere_de_la_porte_rouge', '{}'::jsonb, null, null, true, 17, 1),
    (v_set_id, 'ROY-003', 'Garde du Tambour Royal', 'personnage', null, null, 'commune', 4, 1700, 2000, 'terre', 'royaume', array['village']::text[], null, 'Les autres Personnages Royaume que tu contrôles ne peuvent pas être ciblés par une attaque tant que cette carte est en position d''Attaque.', 'roy_003_garde_du_tambour_royal', '{}'::jsonb, null, null, true, 18, 1),
    (v_set_id, 'ROY-004', 'Stratège des Sept Cours', 'personnage', null, null, 'rare', 4, 1600, 1800, 'esprit', 'royaume', '{}'::text[], null, 'À son invocation : regarde les 3 cartes du dessus de ton deck ; ajoute 1 carte Royaume parmi elles à ta main et replace les autres sous le deck dans l''ordre de ton choix.', 'roy_004_stratege_des_sept_cours', '{}'::jsonb, null, null, true, 19, 1),
    (v_set_id, 'ROY-005', 'Cavalier au Manteau Pourpre', 'personnage', null, null, 'rare', 5, 2200, 1700, 'vent', 'royaume', array['savane']::text[], null, 'Si un Personnage a été sacrifié pour son invocation, cette carte gagne 400 ATK pendant le tour de son invocation.', 'roy_005_cavalier_au_manteau_pourpre', '{}'::jsonb, null, null, true, 20, 1),
    (v_set_id, 'ROY-006', 'Reine des Remparts Solaires', 'personnage', null, null, 'épique', 6, 2300, 2600, 'lumière', 'royaume', '{}'::text[], null, 'Une fois par tour, lorsqu''une carte Royaume que tu contrôles devrait être détruite par un effet : tu peux défausser 1 carte ; elle n''est pas détruite.', 'roy_006_reine_des_remparts_solaires', '{}'::jsonb, null, null, true, 21, 1),
    (v_set_id, 'ROY-007', 'Roi au Serment de Fer', 'personnage', null, null, 'épique', 8, 3000, 2700, 'terre', 'royaume', array['ancêtre']::text[], null, 'À son invocation par sacrifice : cible jusqu''à 2 Personnages Royaume dans ton Cimetière de rang 4 ou moins ; invoque-les spécialement en Défense, effets annulés ce tour.', 'roy_007_roi_au_serment_de_fer', '{}'::jsonb, null, null, true, 22, 1),
    (v_set_id, 'ROY-008', 'Décret de Mobilisation', 'action', 'normal', null, 'commune', null, null, null, 'lumière', 'royaume', '{}'::text[], null, 'Ajoute à ta main 1 Personnage Royaume de rang 4 ou moins depuis ton deck.', 'roy_008_decret_de_mobilisation', '{}'::jsonb, null, null, true, 23, 1),
    (v_set_id, 'ROY-009', 'Relève de la Garde', 'action', 'quick', null, 'rare', null, null, null, 'terre', 'royaume', '{}'::text[], null, 'Lorsqu''un Personnage Royaume devrait être détruit : sacrifie 1 autre Personnage que tu contrôles ; empêche cette destruction.', 'roy_009_releve_de_la_garde', '{}'::jsonb, null, null, true, 24, 1),
    (v_set_id, 'ROY-010', 'Couronnement des Sept Tambours', 'action', 'normal', null, 'épique', null, null, null, 'esprit', 'royaume', array['ancêtre']::text[], null, 'Invocation ancestrale : sacrifie des Personnages que tu contrôles dont le total des rangs est au moins 9 ; invoque spécialement « Souverain des Sept Tambours » depuis ta Réserve des Mythiques.', 'roy_010_couronnement_des_sept_tambours', '{}'::jsonb, null, null, true, 25, 1),
    (v_set_id, 'ROY-011', 'Herse de Lumière', 'piège', 'normal', null, 'commune', null, null, null, 'lumière', 'royaume', '{}'::text[], null, 'Lorsqu''un Personnage adverse déclare une attaque : cible cet attaquant ; il perd 800 ATK ce tour. S''il passe sous l''ATK de sa cible, annule l''attaque.', 'roy_011_herse_de_lumiere', '{}'::jsonb, null, null, true, 26, 1),
    (v_set_id, 'ROY-012', 'Sceau Inviolable', 'piège', 'counter', null, 'rare', null, null, null, 'esprit', 'royaume', array['ancêtre']::text[], null, 'Lorsqu''un effet cible une carte Royaume que tu contrôles : annule l''activation et détruis la carte ayant activé cet effet.', 'roy_012_sceau_inviolable', '{}'::jsonb, null, null, true, 27, 1),
    (v_set_id, 'ROY-013', 'Cour des Mille Étendards', 'terrain', null, null, 'rare', null, null, null, 'terre', 'royaume', array['village']::text[], null, 'Les Personnages Royaume gagnent 200 DEF. Chaque fois que tu sacrifies un Personnage, place 1 marqueur Serment ici. À 3 marqueurs ou plus, tes Personnages Royaume gagnent aussi 300 ATK.', 'roy_013_cour_des_mille_etendards', '{}'::jsonb, null, null, true, 28, 1),
    (v_set_id, 'ROY-014', 'Couronne du Pacte Ancien', 'relique', null, 'equipment', 'épique', null, null, null, 'esprit', 'royaume', array['ancêtre']::text[], null, 'Équipe un Personnage Royaume de rang 5 ou plus. Il gagne 400 ATK/DEF. S''il quitte le terrain, ajoute cette Relique à ta main au lieu de l''envoyer au Cimetière.', 'roy_014_couronne_du_pacte_ancien', '{}'::jsonb, null, null, true, 29, 1),
    (v_set_id, 'ROY-015', 'Souverain des Sept Tambours', 'mythique', null, null, 'légendaire', 10, 3700, 3400, 'esprit', 'royaume', array['ancêtre']::text[], '{"method":"ancestrale","trigger_card_code":"ROY-010","requirements":{"families":["royaume"],"minimum_total_rank":9,"source":"field","payment":"sacrifice"}}'::jsonb, 'Doit d''abord être invoqué par « Couronnement des Sept Tambours ». À son invocation : jusqu''à 2 Personnages Royaume dans ton Cimetière reviennent spécialement en Défense. Une fois par tour : sacrifie 1 autre Personnage ; annule l''activation d''un effet de Vitesse 2 et détruis sa carte.', 'roy_015_souverain_des_sept_tambours', '{}'::jsonb, null, null, true, 30, 1),
    (v_set_id, 'ANC-001', 'Porteur de Cauris', 'personnage', null, null, 'commune', 1, 300, 900, 'esprit', 'ancêtre', array['village']::text[], null, 'Si cette carte est envoyée du terrain au Cimetière : place la carte du dessus de ton deck au Cimetière.', 'anc_001_porteur_de_cauris', '{}'::jsonb, null, null, true, 31, 1),
    (v_set_id, 'ANC-002', 'Enfant des Songes Clairs', 'personnage', null, null, 'commune', 2, 800, 1300, 'lumière', 'ancêtre', array['village']::text[], null, 'À son invocation : cible 1 carte Ancêtre dans ton Cimetière ; place-la sous ton deck.', 'anc_002_enfant_des_songes_clairs', '{}'::jsonb, null, null, true, 32, 1),
    (v_set_id, 'ANC-003', 'Veilleuse du Foyer Invisible', 'personnage', null, null, 'commune', 3, 1300, 1700, 'feu', 'ancêtre', array['village']::text[], null, 'Aucun effet.', 'anc_003_veilleuse_du_foyer_invisible', '{}'::jsonb, null, null, true, 33, 1),
    (v_set_id, 'ANC-004', 'Messager de la Première Pluie', 'personnage', null, null, 'rare', 4, 1700, 1600, 'eau', 'ancêtre', array['lagune']::text[], null, 'À son invocation : envoie 1 carte Ancêtre depuis ton deck au Cimetière, sauf « Messager de la Première Pluie ».', 'anc_004_messager_de_la_premiere_pluie', '{}'::jsonb, null, null, true, 34, 1),
    (v_set_id, 'ANC-005', 'Gardienne des Noms Oubliés', 'personnage', null, null, 'rare', 5, 2100, 2200, 'esprit', 'ancêtre', array['royaume']::text[], null, 'Une fois par tour : cible 1 Personnage de rang 4 ou moins dans ton Cimetière ; mélange cette carte dans le deck et ajoute la cible à ta main.', 'anc_005_gardienne_des_noms_oublies', '{}'::jsonb, null, null, true, 35, 1),
    (v_set_id, 'ANC-006', 'Conseiller de l''Au-Delà', 'personnage', null, null, 'épique', 6, 2300, 2500, 'ombre', 'ancêtre', array['royaume']::text[], null, 'Si cette carte est envoyée au Cimetière comme sacrifice ou coût : tu peux invoquer spécialement 1 Personnage Ancêtre de rang 3 ou moins depuis ton Cimetière.', 'anc_006_conseiller_de_l_au_dela', '{}'::jsonb, null, null, true, 36, 1),
    (v_set_id, 'ANC-007', 'Matriarche aux Cent Mémoires', 'personnage', null, null, 'épique', 8, 2900, 3100, 'esprit', 'ancêtre', array['village']::text[], null, 'À son invocation : cible jusqu''à 3 cartes Ancêtre dans ton Cimetière ; mélange-les dans le deck, puis pioche 1 carte. Cette carte gagne 100 ATK pour chaque carte ainsi mélangée.', 'anc_007_matriarche_aux_cent_memoires', '{}'::jsonb, null, null, true, 37, 1),
    (v_set_id, 'ANC-008', 'Parole Transmise', 'action', 'normal', null, 'commune', null, null, null, 'esprit', 'ancêtre', array['village']::text[], null, 'Ajoute à ta main 1 carte Ancêtre depuis ton Cimetière, puis défausse 1 carte.', 'anc_008_parole_transmise', '{}'::jsonb, null, null, true, 38, 1),
    (v_set_id, 'ANC-009', 'Main des Aïeux', 'action', 'quick', null, 'rare', null, null, null, 'lumière', 'ancêtre', '{}'::text[], null, 'Cible 1 Personnage Ancêtre que tu contrôles et 1 Personnage adverse ; le premier gagne 600 ATK/DEF et le second perd 300 ATK/DEF ce tour.', 'anc_009_main_des_aieux', '{}'::jsonb, null, null, true, 39, 1),
    (v_set_id, 'ANC-010', 'Appel des Huit Veillées', 'action', 'normal', null, 'épique', null, null, null, 'esprit', 'ancêtre', '{}'::text[], null, 'Invocation ancestrale : bannis depuis ton Cimetière des Personnages Ancêtre dont le total des rangs est au moins 10 ; invoque spécialement « Mère des Premières Lueurs » depuis ta Réserve des Mythiques.', 'anc_010_appel_des_huit_veillees', '{}'::jsonb, null, null, true, 40, 1),
    (v_set_id, 'ANC-011', 'Conseil des Invisibles', 'piège', 'normal', null, 'commune', null, null, null, 'esprit', 'ancêtre', '{}'::text[], null, 'Lorsqu''un Personnage que tu contrôles est détruit : invoque spécialement 1 Personnage Ancêtre de rang inférieur depuis ton Cimetière en Défense.', 'anc_011_conseil_des_invisibles', '{}'::jsonb, null, null, true, 41, 1),
    (v_set_id, 'ANC-012', 'Refus de l''Oubli', 'piège', 'counter', null, 'rare', null, null, null, 'lumière', 'ancêtre', array['royaume']::text[], null, 'Lorsqu''une carte de ton Cimetière devrait être bannie par un effet adverse : annule l''activation et détruis sa carte.', 'anc_012_refus_de_l_oubli', '{}'::jsonb, null, null, true, 42, 1),
    (v_set_id, 'ANC-013', 'Bosquet des Voix Anciennes', 'terrain', null, null, 'rare', null, null, null, 'nature', 'ancêtre', array['forêt']::text[], null, 'Une fois par tour, lorsqu''une carte est envoyée de ton terrain au Cimetière : place 1 marqueur Mémoire ici. Retire 3 marqueurs ; pioche 1 carte, puis défausse 1 carte.', 'anc_013_bosquet_des_voix_anciennes', '{}'::jsonb, null, null, true, 43, 1),
    (v_set_id, 'ANC-014', 'Calebasse des Huit Noms', 'relique', null, 'alternative_win', 'légendaire', null, null, null, 'esprit', 'ancêtre', array['village']::text[], null, 'Active cette Relique face visible dans une Zone Action/Piège libre. Chaque fois qu''un Personnage Ancêtre de nom différent est envoyé depuis ton terrain au Cimetière, place 1 marqueur Nom ici. Au début de ta Phase de Préparation, si cette carte possède 8 marqueurs Nom, tu remportes le duel.', 'anc_014_calebasse_des_huit_noms', '{}'::jsonb, null, null, true, 44, 1),
    (v_set_id, 'ANC-015', 'Mère des Premières Lueurs', 'mythique', null, null, 'légendaire', 10, 3500, 3800, 'lumière', 'ancêtre', array['village']::text[], '{"method":"ancestrale","trigger_card_code":"ANC-010","requirements":{"families":["ancêtre"],"minimum_total_rank":10,"source":"graveyard","payment":"banish"}}'::jsonb, 'Doit d''abord être invoquée par « Appel des Huit Veillées ». À son invocation : mélange jusqu''à 5 cartes de ton Cimetière dans le deck, puis gagne 300 PV par carte mélangée. Une fois par tour, si une carte Ancêtre quitte ton terrain : pioche 1 carte.', 'anc_015_mere_des_premieres_lueurs', '{}'::jsonb, null, null, true, 45, 1),
    (v_set_id, 'MAS-001', 'Porte-Masque Novice', 'personnage', null, null, 'commune', 2, 700, 1400, 'esprit', 'masque', array['village']::text[], null, 'Retournement : pioche 1 carte, puis défausse 1 carte.', 'mas_001_porte_masque_novice', '{}'::jsonb, null, null, true, 46, 1),
    (v_set_id, 'MAS-002', 'Danseur aux Pas Croisés', 'personnage', null, null, 'commune', 3, 1400, 1300, 'vent', 'masque', array['babi']::text[], null, 'Une fois par tour : change la position de combat de cette carte. Si elle passe en Défense, elle gagne 300 DEF ce tour.', 'mas_002_danseur_aux_pas_croises', '{}'::jsonb, null, null, true, 47, 1),
    (v_set_id, 'MAS-003', 'Sentinelle au Visage de Bois', 'personnage', null, null, 'commune', 4, 1600, 2100, 'nature', 'masque', array['forêt']::text[], null, 'Aucun effet.', 'mas_003_sentinelle_au_visage_de_bois', '{}'::jsonb, null, null, true, 48, 1),
    (v_set_id, 'MAS-004', 'Rieuse aux Deux Visages', 'personnage', null, null, 'rare', 4, 1700, 1700, 'ombre', 'masque', array['maquis']::text[], null, 'Retournement : cible 1 Personnage face visible adverse ; son ATK et sa DEF sont échangées jusqu''à la fin du tour.', 'mas_004_rieuse_aux_deux_visages', '{}'::jsonb, null, null, true, 49, 1),
    (v_set_id, 'MAS-005', 'Sculpteur des Gestes Secrets', 'personnage', null, null, 'rare', 5, 2100, 2300, 'terre', 'masque', array['village']::text[], null, 'À son invocation : tu peux poser face cachée 1 Personnage Masque de rang 4 ou moins depuis ta main dans une Zone Personnage libre. Cette pose ne consomme pas ta Pose normale.', 'mas_005_sculpteur_des_gestes_secrets', '{}'::jsonb, null, null, true, 50, 1),
    (v_set_id, 'MAS-006', 'Masque Dan, Gardien des Seuils', 'personnage', null, null, 'épique', 6, 2400, 2500, 'esprit', 'masque', array['ancêtre']::text[], null, 'Les Personnages face cachée que tu contrôles ne peuvent pas être ciblés par des effets adverses. Une fois par tour : retourne face cachée en Défense 1 autre Personnage Masque face visible que tu contrôles.', 'mas_006_masque_dan_gardien_des_seuils', '{}'::jsonb, null, null, true, 51, 1),
    (v_set_id, 'MAS-007', 'Maîtresse du Ballet Invisible', 'personnage', null, null, 'épique', 7, 2700, 2800, 'vent', 'masque', array['ancêtre']::text[], null, 'Une fois par tour : cible 1 Personnage sur le terrain ; passe-le en Défense face visible. Si c''était un Personnage Masque que tu contrôles, tu peux ensuite le retourner face cachée.', 'mas_007_maitresse_du_ballet_invisible', '{}'::jsonb, null, null, true, 52, 1),
    (v_set_id, 'MAS-008', 'Changement de Visage', 'action', 'quick', null, 'commune', null, null, null, 'ombre', 'masque', '{}'::text[], null, 'Cible 1 Personnage Masque que tu contrôles ; retourne-le face cachée en Défense ou face visible dans sa position actuelle.', 'mas_008_changement_de_visage', '{}'::jsonb, null, null, true, 53, 1),
    (v_set_id, 'MAS-009', 'Danse de Révélation', 'action', 'normal', null, 'rare', null, null, null, 'lumière', 'masque', '{}'::text[], null, 'Retourne face visible jusqu''à 2 Personnages face cachée sur le terrain. Les effets de retournement des Personnages Masque que tu contrôles ainsi révélés peuvent s''activer.', 'mas_009_danse_de_revelation', '{}'::jsonb, null, null, true, 54, 1),
    (v_set_id, 'MAS-010', 'Rythme des Mille Visages', 'action', 'normal', null, 'épique', null, null, null, 'esprit', 'masque', array['ancêtre']::text[], null, 'Invocation Fusion : envoie depuis ton terrain au Cimetière « Rieuse aux Deux Visages » et « Masque Dan, Gardien des Seuils » ; invoque spécialement « Masque du Premier Rythme » depuis ta Réserve des Mythiques.', 'mas_010_rythme_des_mille_visages', '{}'::jsonb, null, null, true, 55, 1),
    (v_set_id, 'MAS-011', 'Faux Mouvement', 'piège', 'normal', null, 'commune', null, null, null, 'vent', 'masque', '{}'::text[], null, 'Lorsqu''un Personnage adverse cible un Personnage face cachée pour une attaque : change la cible vers un autre Personnage que tu contrôles, si possible.', 'mas_011_faux_mouvement', '{}'::jsonb, null, null, true, 56, 1),
    (v_set_id, 'MAS-012', 'Visage Interdit', 'piège', 'counter', null, 'rare', null, null, null, 'ombre', 'masque', array['dozo']::text[], null, 'Lorsqu''un effet adverse doit révéler ou retourner face visible une de tes cartes face cachée : annule l''activation et détruis sa carte.', 'mas_012_visage_interdit', '{}'::jsonb, null, null, true, 57, 1),
    (v_set_id, 'MAS-013', 'Place des Danses Secrètes', 'terrain', null, null, 'rare', null, null, null, 'esprit', 'masque', array['village']::text[], null, 'Les Personnages Masque gagnent 200 DEF. La première fois par tour qu''un Personnage est retourné face visible, son contrôleur gagne 300 PV.', 'mas_013_place_des_danses_secretes', '{}'::jsonb, null, null, true, 58, 1),
    (v_set_id, 'MAS-014', 'Ciseau du Maître Sculpteur', 'relique', null, 'equipment', 'épique', null, null, null, 'terre', 'masque', array['village']::text[], null, 'Équipe un Personnage Masque. Il gagne 300 ATK/DEF. Une fois par tour, s''il a été retourné face visible ce tour : tu peux poser 1 Piège depuis ta main.', 'mas_014_ciseau_du_maitre_sculpteur', '{}'::jsonb, null, null, true, 59, 1),
    (v_set_id, 'MAS-015', 'Masque du Premier Rythme', 'mythique', null, null, 'légendaire', 9, 3100, 3300, 'esprit', 'masque', array['ancêtre']::text[], '{"method":"fusion","trigger_card_code":"MAS-010","source":"field","destination":"graveyard","materials":[{"card_code":"MAS-004","quantity":1},{"card_code":"MAS-006","quantity":1}]}'::jsonb, 'Doit d''abord être invoqué par « Rythme des Mille Visages ». À son invocation : retourne face cachée en Défense jusqu''à 2 Personnages adverses. Une fois par tour, lorsqu''une carte est retournée face visible : annule ses effets jusqu''à la fin du tour ou fais gagner 500 ATK à cette carte ce tour.', 'mas_015_masque_du_premier_rythme', '{}'::jsonb, null, null, true, 60, 1),
    (v_set_id, 'DOZ-001', 'Apprenti Pisteur', 'personnage', null, null, 'commune', 1, 500, 800, 'nature', 'dozo', array['forêt']::text[], null, 'À son invocation : regarde la carte du dessus du deck adverse et replace-la au-dessus.', 'doz_001_apprenti_pisteur', '{}'::jsonb, null, null, true, 61, 1),
    (v_set_id, 'DOZ-002', 'Archère des Hautes Herbes', 'personnage', null, null, 'commune', 3, 1500, 1000, 'vent', 'dozo', array['savane']::text[], null, 'Si elle attaque un Personnage en Défense, elle gagne 300 ATK pendant le calcul des dégâts uniquement.', 'doz_002_archere_des_hautes_herbes', '{}'::jsonb, null, null, true, 62, 1),
    (v_set_id, 'DOZ-003', 'Gardien au Fusil Rituel', 'personnage', null, null, 'commune', 4, 1800, 1800, 'feu', 'dozo', array['savane']::text[], null, 'Aucun effet.', 'doz_003_gardien_au_fusil_rituel', '{}'::jsonb, null, null, true, 63, 1),
    (v_set_id, 'DOZ-004', 'Lecteur de Traces', 'personnage', null, null, 'rare', 4, 1600, 1900, 'terre', 'dozo', array['forêt']::text[], null, 'À son invocation : ajoute à ta main 1 Piège Dozo depuis ton deck, puis place 1 carte de ta main sous ton deck.', 'doz_004_lecteur_de_traces', '{}'::jsonb, null, null, true, 64, 1),
    (v_set_id, 'DOZ-005', 'Chasseuse au Manteau Brun', 'personnage', null, null, 'rare', 5, 2200, 1900, 'nature', 'dozo', array['savane']::text[], null, 'Une fois par tour : cible 1 Personnage adverse face visible ; place 1 marqueur Proie sur lui. Cette carte gagne 300 ATK lorsqu''elle combat un Personnage avec un marqueur Proie.', 'doz_005_chasseuse_au_manteau_brun', '{}'::jsonb, null, null, true, 65, 1),
    (v_set_id, 'DOZ-006', 'Maître des Collets', 'personnage', null, null, 'épique', 6, 2300, 2600, 'terre', 'dozo', array['forêt']::text[], null, 'Tu peux activer les Pièges Dozo le tour où ils sont posés, mais seulement pendant ton propre tour. Une seule fois par tour.', 'doz_006_maitre_des_collets', '{}'::jsonb, null, null, true, 66, 1),
    (v_set_id, 'DOZ-007', 'Capitaine de la Chasse Nocturne', 'personnage', null, null, 'épique', 8, 3000, 2800, 'ombre', 'dozo', array['savane']::text[], null, 'À son invocation : place 1 marqueur Proie sur chaque Personnage adverse face visible. Une fois par tour, après la destruction au combat d''une Proie : bannis cette Proie au lieu de l''envoyer au Cimetière.', 'doz_007_capitaine_de_la_chasse_nocturne', '{}'::jsonb, null, null, true, 67, 1),
    (v_set_id, 'DOZ-008', 'Piste Fraîche', 'action', 'normal', null, 'commune', null, null, null, 'terre', 'dozo', '{}'::text[], null, 'Cible 1 Personnage adverse face visible ; place 1 marqueur Proie sur lui, puis ajoute à ta main 1 Personnage Dozo de rang 4 ou moins depuis ton deck.', 'doz_008_piste_fraiche', '{}'::jsonb, null, null, true, 68, 1),
    (v_set_id, 'DOZ-009', 'Tir de Sommation', 'action', 'quick', null, 'rare', null, null, null, 'feu', 'dozo', '{}'::text[], null, 'Cible 1 Personnage avec un marqueur Proie ; il perd 700 ATK ce tour. S''il est en Défense, il perd aussi 700 DEF ce tour.', 'doz_009_tir_de_sommation', '{}'::jsonb, null, null, true, 69, 1),
    (v_set_id, 'DOZ-010', 'Serment de la Lune des Chasseurs', 'action', 'normal', null, 'épique', null, null, null, 'ombre', 'dozo', array['ancêtre']::text[], null, 'Invocation ancestrale : sacrifie 1 Personnage Dozo de rang 6 ou plus et bannis 2 Pièges depuis ton Cimetière ; invoque spécialement « Maître Dozo de la Lune Noire » depuis ta Réserve des Mythiques.', 'doz_010_serment_de_la_lune_des_chasseurs', '{}'::jsonb, null, null, true, 70, 1),
    (v_set_id, 'DOZ-011', 'Collet des Hautes Herbes', 'piège', 'normal', null, 'commune', null, null, null, 'nature', 'dozo', array['savane']::text[], null, 'Lorsqu''un Personnage adverse déclare une attaque : cible l''attaquant ; annule l''attaque, passe-le en Défense et place 1 marqueur Proie sur lui.', 'doz_011_collet_des_hautes_herbes', '{}'::jsonb, null, null, true, 71, 1),
    (v_set_id, 'DOZ-012', 'Dernier Coup de Sifflet', 'piège', 'counter', null, 'rare', null, null, null, 'vent', 'dozo', '{}'::text[], null, 'Lorsqu''un effet d''un Personnage avec un marqueur Proie est activé : annule l''activation et bannis ce Personnage.', 'doz_012_dernier_coup_de_sifflet', '{}'::jsonb, null, null, true, 72, 1),
    (v_set_id, 'DOZ-013', 'Campement sous la Lune', 'terrain', null, null, 'rare', null, null, null, 'ombre', 'dozo', array['savane']::text[], null, 'Les Personnages Dozo gagnent 200 ATK/DEF. Une fois par tour, lorsqu''un Piège est activé : place 1 marqueur Proie sur 1 Personnage adverse face visible.', 'doz_013_campement_sous_la_lune', '{}'::jsonb, null, null, true, 73, 1),
    (v_set_id, 'DOZ-014', 'Corne du Premier Buffle', 'relique', null, 'equipment', 'épique', null, null, null, 'terre', 'dozo', array['savane']::text[], null, 'Équipe un Personnage Dozo. Il gagne 400 ATK. Lorsqu''il détruit une Proie au combat : tu peux poser 1 Piège Dozo directement depuis ta main.', 'doz_014_corne_du_premier_buffle', '{}'::jsonb, null, null, true, 74, 1),
    (v_set_id, 'DOZ-015', 'Maître Dozo de la Lune Noire', 'mythique', null, null, 'légendaire', 10, 3600, 3500, 'ombre', 'dozo', array['ancêtre']::text[], '{"method":"ancestrale","trigger_card_code":"DOZ-010","requirements":{"all":[{"kind":"character","families":["dozo"],"minimum_rank":6,"quantity":1,"source":"field","payment":"sacrifice"},{"kind":"trap","quantity":2,"source":"graveyard","payment":"banish"}]}}'::jsonb, 'Doit d''abord être invoqué par « Serment de la Lune des Chasseurs ». Les Personnages adverses avec un marqueur Proie ne peuvent pas cibler d''autres cartes que celle-ci avec leurs attaques. Une fois par tour : bannis 1 Proie face visible, mais cette carte ne peut pas attaquer ce tour.', 'doz_015_maitre_dozo_de_la_lune_noire', '{}'::jsonb, null, null, true, 75, 1),
    (v_set_id, 'FOR-001', 'Graine Qui Marche', 'personnage', null, null, 'commune', 1, 300, 600, 'nature', 'forêt', '{}'::text[], null, 'Si cette carte est envoyée du terrain au Cimetière : crée 1 Jeton Sylve en Défense (Nature, rang 1, 500 ATK/500 DEF).', 'for_001_graine_qui_marche', '{}'::jsonb, null, null, true, 76, 1),
    (v_set_id, 'FOR-002', 'Singe aux Fruits d''Or', 'personnage', null, null, 'commune', 2, 1000, 900, 'nature', 'forêt', array['savane']::text[], null, 'Une fois par tour, si tu gagnes des PV : cette carte gagne 300 ATK jusqu''à la fin du tour.', 'for_002_singe_aux_fruits_d_or', '{}'::jsonb, null, null, true, 77, 1),
    (v_set_id, 'FOR-003', 'Antilope des Sous-Bois', 'personnage', null, null, 'commune', 3, 1500, 1400, 'vent', 'forêt', array['savane']::text[], null, 'Aucun effet.', 'for_003_antilope_des_sous_bois', '{}'::jsonb, null, null, true, 78, 1),
    (v_set_id, 'FOR-004', 'Guérisseuse des Lianes', 'personnage', null, null, 'rare', 4, 1500, 2000, 'nature', 'forêt', array['village']::text[], null, 'À son invocation : gagne 500 PV. Une fois par tour, lorsqu''un Jeton est créé sur ton terrain : gagne 200 PV.', 'for_004_guerisseuse_des_lianes', '{}'::jsonb, null, null, true, 79, 1),
    (v_set_id, 'FOR-005', 'Panthère des Racines', 'personnage', null, null, 'rare', 5, 2200, 1800, 'ombre', 'forêt', array['savane']::text[], null, 'Cette carte peut attaquer directement si tu contrôles un Jeton Sylve, mais les dégâts de cette attaque sont divisés par deux, arrondis au supérieur.', 'for_005_panthere_des_racines', '{}'::jsonb, null, null, true, 80, 1),
    (v_set_id, 'FOR-006', 'Gardien Iroko', 'personnage', null, null, 'épique', 6, 2300, 2800, 'terre', 'forêt', array['ancêtre']::text[], null, 'Une fois par tour : sacrifie 1 Jeton ; empêche la destruction d''une carte Forêt que tu contrôles.', 'for_006_gardien_iroko', '{}'::jsonb, null, null, true, 81, 1),
    (v_set_id, 'FOR-007', 'Éléphante aux Jardins Vivants', 'personnage', null, null, 'épique', 8, 2900, 3200, 'nature', 'forêt', array['savane']::text[], null, 'À son invocation : crée jusqu''à 2 Jetons Sylve en Défense. Les Jetons que tu contrôles gagnent 300 DEF.', 'for_007_elephante_aux_jardins_vivants', '{}'::jsonb, null, null, true, 82, 1),
    (v_set_id, 'FOR-008', 'Germination Soudaine', 'action', 'quick', null, 'commune', null, null, null, 'nature', 'forêt', '{}'::text[], null, 'Crée 1 Jeton Sylve en Défense. Il ne peut pas être sacrifié pendant ce tour.', 'for_008_germination_soudaine', '{}'::jsonb, null, null, true, 83, 1),
    (v_set_id, 'FOR-009', 'Saison des Grandes Pluies', 'action', 'continuous', null, 'rare', null, null, null, 'eau', 'forêt', array['lagune']::text[], null, 'À chaque Phase de Préparation de ton tour : place 1 marqueur Graine ici. Retire 2 marqueurs ; crée 1 Jeton Sylve ou gagne 500 PV.', 'for_009_saison_des_grandes_pluies', '{}'::jsonb, null, null, true, 84, 1),
    (v_set_id, 'FOR-010', 'Racines du Cœur-Monde', 'action', 'normal', null, 'épique', null, null, null, 'esprit', 'forêt', array['ancêtre']::text[], null, 'Invocation Fusion : envoie depuis ton terrain au Cimetière « Gardien Iroko » et 2 Jetons Sylve ; invoque spécialement « Iroko, Cœur du Monde » depuis ta Réserve des Mythiques.', 'for_010_racines_du_coeur_monde', '{}'::jsonb, null, null, true, 85, 1),
    (v_set_id, 'FOR-011', 'Liane Entravante', 'piège', 'normal', null, 'commune', null, null, null, 'nature', 'forêt', '{}'::text[], null, 'Lorsqu''un Personnage adverse déclare une attaque : cible l''attaquant ; annule l''attaque et il ne peut pas changer de position pendant son prochain tour.', 'for_011_liane_entravante', '{}'::jsonb, null, null, true, 86, 1),
    (v_set_id, 'FOR-012', 'Reprise Sauvage', 'piège', 'continuous', null, 'rare', null, null, null, 'nature', 'forêt', array['ancêtre']::text[], null, 'Une fois par tour, lorsqu''un Personnage Forêt que tu contrôles est détruit : crée 1 Jeton Sylve en Défense.', 'for_012_reprise_sauvage', '{}'::jsonb, null, null, true, 87, 1),
    (v_set_id, 'FOR-013', 'Forêt aux Mille Souffles', 'terrain', null, null, 'rare', null, null, null, 'nature', 'forêt', array['ancêtre']::text[], null, 'Les Personnages Forêt gagnent 200 ATK/DEF. Les Jetons Sylve gagnent 300 ATK/DEF supplémentaires.', 'for_013_foret_aux_mille_souffles', '{}'::jsonb, null, null, true, 88, 1),
    (v_set_id, 'FOR-014', 'Graine de l''Arbre Originel', 'relique', null, 'action', 'épique', null, null, null, 'esprit', 'forêt', array['ancêtre']::text[], null, 'Place cette Relique face visible dans une Zone Action/Piège libre. À ta troisième Phase de Préparation après son activation, envoie-la au Cimetière ; invoque spécialement 1 Personnage Forêt de rang 7 ou 8 depuis ton deck, effets annulés ce tour.', 'for_014_graine_de_l_arbre_originel', '{}'::jsonb, null, null, true, 89, 1),
    (v_set_id, 'FOR-015', 'Iroko, Cœur du Monde', 'mythique', null, null, 'légendaire', 10, 3500, 4000, 'nature', 'forêt', array['ancêtre']::text[], '{"method":"fusion","trigger_card_code":"FOR-010","source":"field","destination":"graveyard","materials":[{"card_code":"FOR-006","quantity":1},{"token_key":"sylve","quantity":2}]}'::jsonb, 'Doit d''abord être invoqué par « Racines du Cœur-Monde ». À son invocation : crée autant de Jetons Sylve que possible, jusqu''à 3. Une fois par tour : sacrifie 1 Jeton ; gagne 800 PV et cette carte gagne 400 ATK ce tour.', 'for_015_iroko_coeur_du_monde', '{}'::jsonb, null, null, true, 90, 1),
    (v_set_id, 'LAG-001', 'Petit Piroguier des Brumes', 'personnage', null, null, 'commune', 1, 500, 700, 'eau', 'lagune', array['village']::text[], null, 'Si cette carte est renvoyée du terrain dans ta main par un effet : pioche 1 carte, puis défausse 1 carte.', 'lag_001_petit_piroguier_des_brumes', '{}'::jsonb, null, null, true, 91, 1),
    (v_set_id, 'LAG-002', 'Crabe Gardien des Berges', 'personnage', null, null, 'commune', 2, 700, 1500, 'eau', 'lagune', array['forêt']::text[], null, 'Une fois par tour, lorsqu''il passe en Défense : il gagne 300 DEF jusqu''à la fin du tour.', 'lag_002_crabe_gardien_des_berges', '{}'::jsonb, null, null, true, 92, 1),
    (v_set_id, 'LAG-003', 'Crocodile de la Lagune Calme', 'personnage', null, null, 'commune', 4, 1900, 1700, 'eau', 'lagune', array['savane']::text[], null, 'Aucun effet.', 'lag_003_crocodile_de_la_lagune_calme', '{}'::jsonb, null, null, true, 93, 1),
    (v_set_id, 'LAG-004', 'Plongeuse aux Perles Bleues', 'personnage', null, null, 'rare', 4, 1600, 1800, 'eau', 'lagune', array['village']::text[], null, 'À son invocation : cible 1 carte Lagune dans ton Cimetière ; place-la sous ton deck, puis gagne 300 PV.', 'lag_004_plongeuse_aux_perles_bleues', '{}'::jsonb, null, null, true, 94, 1),
    (v_set_id, 'LAG-005', 'Gardienne des Palétuviers', 'personnage', null, null, 'rare', 5, 2100, 2400, 'nature', 'lagune', array['forêt']::text[], null, 'Une fois par tour : renvoie 1 autre carte Lagune que tu contrôles dans ta main ; cible 1 Personnage adverse face visible et passe-le en Défense.', 'lag_005_gardienne_des_paletuviers', '{}'::jsonb, null, null, true, 95, 1),
    (v_set_id, 'LAG-006', 'Prince des Courants Croisés', 'personnage', null, null, 'épique', 6, 2500, 2200, 'eau', 'lagune', array['royaume']::text[], null, 'Lorsqu''une carte est renvoyée du terrain dans une main : cette carte gagne 300 ATK jusqu''à la fin du tour. Cet effet peut s''appliquer deux fois par tour.', 'lag_006_prince_des_courants_croises', '{}'::jsonb, null, null, true, 96, 1),
    (v_set_id, 'LAG-007', 'Hippopotame des Eaux Profondes', 'personnage', null, null, 'épique', 8, 2900, 3300, 'eau', 'lagune', array['savane']::text[], null, 'Ne peut pas être renvoyé dans une main par un effet adverse. Une fois par tour : renvoie 1 autre carte que tu contrôles dans ta main ; détruis 1 Action ou Piège face visible adverse.', 'lag_007_hippopotame_des_eaux_profondes', '{}'::jsonb, null, null, true, 97, 1),
    (v_set_id, 'LAG-008', 'Courant Inverse', 'action', 'quick', null, 'commune', null, null, null, 'eau', 'lagune', '{}'::text[], null, 'Cible 1 Personnage Lagune que tu contrôles et 1 Personnage adverse de rang inférieur ou égal ; renvoie les deux dans la main de leur propriétaire.', 'lag_008_courant_inverse', '{}'::jsonb, null, null, true, 98, 1),
    (v_set_id, 'LAG-009', 'Marée des Palétuviers', 'action', 'continuous', null, 'rare', null, null, null, 'nature', 'lagune', array['forêt']::text[], null, 'Une fois par tour, lorsqu''une carte Lagune revient dans ta main depuis le terrain : gagne 400 PV et tu peux changer la position d''un Personnage sur le terrain.', 'lag_009_maree_des_paletuviers', '{}'::jsonb, null, null, true, 99, 1),
    (v_set_id, 'LAG-010', 'Chant de la Lagune Sans Fond', 'action', 'normal', null, 'épique', null, null, null, 'esprit', 'lagune', array['ancêtre']::text[], null, 'Invocation ancestrale : sacrifie des Personnages Eau dont le total des rangs est au moins 9 et renvoie 1 carte de ton terrain dans ta main ; invoque spécialement « Reine des Eaux d''Ébène » depuis ta Réserve des Mythiques.', 'lag_010_chant_de_la_lagune_sans_fond', '{}'::jsonb, null, null, true, 100, 1),
    (v_set_id, 'LAG-011', 'Filet des Piroguiers', 'piège', 'normal', null, 'commune', null, null, null, 'eau', 'lagune', array['village']::text[], null, 'Lorsqu''un Personnage adverse est invoqué : s''il est de rang 5 ou moins, passe-le en Défense et annule ses effets jusqu''à la fin du tour.', 'lag_011_filet_des_piroguiers', '{}'::jsonb, null, null, true, 101, 1),
    (v_set_id, 'LAG-012', 'Reflux Absolu', 'piège', 'counter', null, 'rare', null, null, null, 'eau', 'lagune', '{}'::text[], null, 'Lorsqu''un effet doit détruire une carte Lagune que tu contrôles : renvoie cette carte dans ta main ; annule l''effet qui devait la détruire.', 'lag_012_reflux_absolu', '{}'::jsonb, null, null, true, 102, 1),
    (v_set_id, 'LAG-013', 'Lagune aux Reflets d''Argent', 'terrain', null, null, 'rare', null, null, null, 'eau', 'lagune', array['ancêtre']::text[], null, 'Les Personnages Lagune gagnent 200 DEF. La première fois par tour qu''une carte revient dans une main depuis le terrain, son propriétaire pioche 1 carte puis défausse 1 carte.', 'lag_013_lagune_aux_reflets_d_argent', '{}'::jsonb, null, null, true, 103, 1),
    (v_set_id, 'LAG-014', 'Pagaie des Deux Rives', 'relique', null, 'equipment', 'épique', null, null, null, 'vent', 'lagune', array['village']::text[], null, 'Équipe un Personnage Lagune. Il gagne 300 ATK/DEF. Une fois par tour : renvoie cette Relique dans ta main ; le Personnage équipé ne peut pas être détruit au combat ce tour.', 'lag_014_pagaie_des_deux_rives', '{}'::jsonb, null, null, true, 104, 1),
    (v_set_id, 'LAG-015', 'Reine des Eaux d''Ébène', 'mythique', null, null, 'légendaire', 9, 3300, 3600, 'eau', 'lagune', array['ancêtre']::text[], '{"method":"ancestrale","trigger_card_code":"LAG-010","requirements":{"all":[{"kind":"character","attributes":["eau"],"minimum_total_rank":9,"source":"field","payment":"sacrifice"},{"kind":"card","quantity":1,"source":"own_field","payment":"return_to_hand"}]}}'::jsonb, 'Doit d''abord être invoquée par « Chant de la Lagune Sans Fond ». À son invocation : renvoie jusqu''à 2 cartes adverses face visible dans la main de leur propriétaire. Une fois par tour, lorsqu''une carte revient dans une main : cible 1 carte sur le terrain ; elle ne peut ni attaquer ni activer ses effets ce tour.', 'lag_015_reine_des_eaux_d_ebene', '{}'::jsonb, null, null, true, 105, 1),
    (v_set_id, 'SAV-001', 'Suricate de l''Aube', 'personnage', null, null, 'commune', 1, 600, 500, 'terre', 'savane', array['forêt']::text[], null, 'À son invocation : regarde la carte du dessus de ton deck. Si c''est un Personnage Savane, tu peux la révéler et l''ajouter à ta main, puis place 1 carte de ta main sous le deck.', 'sav_001_suricate_de_l_aube', '{}'::jsonb, null, null, true, 106, 1),
    (v_set_id, 'SAV-002', 'Gazelle aux Sabots de Vent', 'personnage', null, null, 'commune', 3, 1500, 900, 'vent', 'savane', array['forêt']::text[], null, 'Si elle attaque directement, elle gagne 300 ATK pendant le calcul des dégâts uniquement.', 'sav_002_gazelle_aux_sabots_de_vent', '{}'::jsonb, null, null, true, 107, 1),
    (v_set_id, 'SAV-003', 'Buffle des Plaines Rouges', 'personnage', null, null, 'commune', 4, 2000, 1600, 'terre', 'savane', array['dozo']::text[], null, 'Aucun effet.', 'sav_003_buffle_des_plaines_rouges', '{}'::jsonb, null, null, true, 108, 1),
    (v_set_id, 'SAV-004', 'Hyène au Rire de Feu', 'personnage', null, null, 'rare', 4, 1800, 1400, 'feu', 'savane', array['maquis']::text[], null, 'Lorsqu''un autre Personnage Savane détruit un adversaire au combat : cette carte peut attaquer une fois supplémentaire ce tour, mais uniquement un Personnage.', 'sav_004_hyene_au_rire_de_feu', '{}'::jsonb, null, null, true, 109, 1),
    (v_set_id, 'SAV-005', 'Éclaireuse des Termitières', 'personnage', null, null, 'rare', 5, 2200, 2000, 'terre', 'savane', array['dozo']::text[], null, 'À son invocation : cible 1 Personnage adverse ; il perd 300 ATK pour chaque autre Personnage Savane que tu contrôles, jusqu''à la fin du tour.', 'sav_005_eclaireuse_des_termitieres', '{}'::jsonb, null, null, true, 110, 1),
    (v_set_id, 'SAV-006', 'Éléphant au Front d''Orage', 'personnage', null, null, 'épique', 6, 2600, 2400, 'vent', 'savane', array['forêt']::text[], null, 'Lorsqu''il attaque un Personnage en Défense, si son ATK dépasse la DEF adverse, inflige à l''adversaire la moitié de la différence en dégâts, arrondie au supérieur.', 'sav_006_elephant_au_front_d_orage', '{}'::jsonb, null, null, true, 111, 1),
    (v_set_id, 'SAV-007', 'Lionne Commandante', 'personnage', null, null, 'épique', 8, 3100, 2700, 'feu', 'savane', array['royaume']::text[], null, 'Les autres Personnages Savane gagnent 300 ATK pendant ta Phase de Combat. Une fois par tour, après qu''un autre Personnage Savane a attaqué : change sa position en Défense.', 'sav_007_lionne_commandante', '{}'::jsonb, null, null, true, 112, 1),
    (v_set_id, 'SAV-008', 'Ruée de la Meute', 'action', 'normal', null, 'commune', null, null, null, 'terre', 'savane', '{}'::text[], null, 'Jusqu''à 3 Personnages Savane que tu contrôles gagnent 300 ATK ce tour. Après leur attaque, ils passent en Défense.', 'sav_008_ruee_de_la_meute', '{}'::jsonb, null, null, true, 113, 1),
    (v_set_id, 'SAV-009', 'Bond au Dernier Instant', 'action', 'quick', null, 'rare', null, null, null, 'vent', 'savane', '{}'::text[], null, 'Pendant la Phase de Combat : cible 1 Personnage Savane ; il gagne 700 ATK pendant ce calcul des dégâts uniquement.', 'sav_009_bond_au_dernier_instant', '{}'::jsonb, null, null, true, 114, 1),
    (v_set_id, 'SAV-010', 'Rugissement du Soleil Premier', 'action', 'normal', null, 'épique', null, null, null, 'feu', 'savane', array['ancêtre']::text[], null, 'Invocation Fusion : envoie depuis ton terrain au Cimetière « Éléphant au Front d''Orage » et « Lionne Commandante » ; invoque spécialement « Lion-Soleil des Plaines Infinies » depuis ta Réserve des Mythiques.', 'sav_010_rugissement_du_soleil_premier', '{}'::jsonb, null, null, true, 115, 1),
    (v_set_id, 'SAV-011', 'Poussière Aveuglante', 'piège', 'normal', null, 'commune', null, null, null, 'vent', 'savane', '{}'::text[], null, 'Lorsqu''un Personnage adverse déclare une attaque : il perd 1000 ATK pendant ce combat. Après le combat, s''il est encore sur le terrain, passe-le en Défense.', 'sav_011_poussiere_aveuglante', '{}'::jsonb, null, null, true, 116, 1),
    (v_set_id, 'SAV-012', 'Cercle des Défenses', 'piège', 'continuous', null, 'rare', null, null, null, 'terre', 'savane', array['royaume']::text[], null, 'Une fois par tour, lorsqu''un Personnage Savane est ciblé par une attaque : tu peux transférer cette attaque vers un autre Personnage Savane que tu contrôles.', 'sav_012_cercle_des_defenses', '{}'::jsonb, null, null, true, 117, 1),
    (v_set_id, 'SAV-013', 'Plaine du Soleil Rouge', 'terrain', null, null, 'rare', null, null, null, 'feu', 'savane', array['dozo']::text[], null, 'Les Personnages Savane gagnent 300 ATK pendant leur Phase de Combat et perdent 100 DEF. Lorsqu''un Personnage Savane détruit un adversaire au combat, son contrôleur gagne 200 PV.', 'sav_013_plaine_du_soleil_rouge', '{}'::jsonb, null, null, true, 118, 1),
    (v_set_id, 'SAV-014', 'Lance de la Première Chasse', 'relique', null, 'equipment', 'épique', null, null, null, 'feu', 'savane', array['dozo']::text[], null, 'Équipe un Personnage Savane. Il gagne 500 ATK lorsqu''il combat un Personnage de rang supérieur au sien. S''il détruit ce Personnage, pioche 1 carte.', 'sav_014_lance_de_la_premiere_chasse', '{}'::jsonb, null, null, true, 119, 1),
    (v_set_id, 'SAV-015', 'Lion-Soleil des Plaines Infinies', 'mythique', null, null, 'légendaire', 10, 3900, 3200, 'feu', 'savane', array['ancêtre']::text[], '{"method":"fusion","trigger_card_code":"SAV-010","source":"field","destination":"graveyard","materials":[{"card_code":"SAV-006","quantity":1},{"card_code":"SAV-007","quantity":1}]}'::jsonb, 'Doit d''abord être invoqué par « Rugissement du Soleil Premier ». Une fois par tour, après avoir détruit un Personnage au combat : cette carte peut attaquer un autre Personnage. Elle ne peut jamais effectuer plus de 2 attaques par tour.', 'sav_015_lion_soleil_des_plaines_infinies', '{}'::jsonb, null, null, true, 120, 1),
    (v_set_id, 'VIL-001', 'Apprenti Potier', 'personnage', null, null, 'commune', 1, 400, 900, 'terre', 'village', '{}'::text[], null, 'Si cette carte est envoyée du terrain au Cimetière : cible 1 Action Équipement ou Relique Équipement dans ton Cimetière ; place-la sous ton deck.', 'vil_001_apprenti_potier', '{}'::jsonb, null, null, true, 121, 1),
    (v_set_id, 'VIL-002', 'Tisserande aux Fils de Vent', 'personnage', null, null, 'commune', 2, 800, 1400, 'vent', 'village', array['babi']::text[], null, 'À son invocation : cible 1 Personnage Village ; il gagne 300 DEF jusqu''à la fin du prochain tour adverse.', 'vil_002_tisserande_aux_fils_de_vent', '{}'::jsonb, null, null, true, 122, 1),
    (v_set_id, 'VIL-003', 'Maçon du Mur de Banco', 'personnage', null, null, 'commune', 4, 1600, 2200, 'terre', 'village', array['royaume']::text[], null, 'Aucun effet.', 'vil_003_macon_du_mur_de_banco', '{}'::jsonb, null, null, true, 123, 1),
    (v_set_id, 'VIL-004', 'Forgeronne des Étincelles Bleues', 'personnage', null, null, 'rare', 4, 1800, 1700, 'feu', 'village', array['royaume']::text[], null, 'À son invocation : ajoute à ta main 1 carte Équipement depuis ton deck, puis défausse 1 carte.', 'vil_004_forgeronne_des_etincelles_bleues', '{}'::jsonb, null, null, true, 124, 1),
    (v_set_id, 'VIL-005', 'Doyenne du Grenier Commun', 'personnage', null, null, 'rare', 5, 2000, 2500, 'nature', 'village', array['ancêtre']::text[], null, 'Une fois par tour, lorsqu''une carte équipée que tu contrôles quitte le terrain : gagne 500 PV et pioche 1 carte, puis défausse 1 carte.', 'vil_005_doyenne_du_grenier_commun', '{}'::jsonb, null, null, true, 125, 1),
    (v_set_id, 'VIL-006', 'Maître Artisan des Trois Métaux', 'personnage', null, null, 'épique', 6, 2400, 2500, 'feu', 'village', array['royaume']::text[], null, 'Une fois par tour : cible 1 Équipement dans ton Cimetière ; équipe-le à une cible légale que tu contrôles. Bannit cet Équipement lorsqu''il quitte ensuite le terrain.', 'vil_006_maitre_artisan_des_trois_metaux', '{}'::jsonb, null, null, true, 126, 1),
    (v_set_id, 'VIL-007', 'Gardien du Grenier d''Argile', 'personnage', null, null, 'épique', 8, 2800, 3400, 'terre', 'village', array['royaume']::text[], null, 'Les autres cartes Village que tu contrôles ne peuvent pas être détruites par des effets adverses une fois par tour. Cette protection s''applique à la première destruction concernée de chaque tour.', 'vil_007_gardien_du_grenier_d_argile', '{}'::jsonb, null, null, true, 127, 1),
    (v_set_id, 'VIL-008', 'Atelier Partagé', 'action', 'continuous', null, 'commune', null, null, null, 'terre', 'village', '{}'::text[], null, 'Une fois par tour, lorsqu''un Équipement est attaché à un Personnage : place 1 marqueur Outil ici. Retire 2 marqueurs ; pioche 1 carte, puis défausse 1 carte.', 'vil_008_atelier_partage', '{}'::jsonb, null, null, true, 128, 1),
    (v_set_id, 'VIL-009', 'Tablier aux Cent Poches', 'action', 'equipment', null, 'rare', null, null, null, 'terre', 'village', '{}'::text[], null, 'Équipe un Personnage Village. Il gagne 400 DEF. Une fois par tour : regarde la carte du dessus de ton deck ; si c''est un Équipement, tu peux la révéler et l''ajouter à ta main, puis place 1 carte de ta main sous le deck.', 'vil_009_tablier_aux_cent_poches', '{}'::jsonb, null, null, true, 129, 1),
    (v_set_id, 'VIL-010', 'Étincelle de la Forge Ancestrale', 'action', 'normal', null, 'épique', null, null, null, 'esprit', 'village', array['ancêtre']::text[], null, 'Invocation Fusion : envoie depuis ton terrain au Cimetière « Forgeronne des Étincelles Bleues », « Maître Artisan des Trois Métaux » et 1 Équipement ; invoque spécialement « Forge-Ancêtre, Main du Peuple » depuis ta Réserve des Mythiques.', 'vil_010_etincelle_de_la_forge_ancestrale', '{}'::jsonb, null, null, true, 130, 1),
    (v_set_id, 'VIL-011', 'Mur de Banco Renforcé', 'piège', 'normal', null, 'commune', null, null, null, 'terre', 'village', array['royaume']::text[], null, 'Lorsqu''un Personnage Village en Défense est attaqué : il gagne 1000 DEF pendant ce combat.', 'vil_011_mur_de_banco_renforce', '{}'::jsonb, null, null, true, 131, 1),
    (v_set_id, 'VIL-012', 'Travail Bien Fait', 'piège', 'counter', null, 'rare', null, null, null, 'lumière', 'village', '{}'::text[], null, 'Lorsqu''un effet doit détruire ou bannir un Équipement que tu contrôles : annule l''activation et détruis sa carte.', 'vil_012_travail_bien_fait', '{}'::jsonb, null, null, true, 132, 1),
    (v_set_id, 'VIL-013', 'Grand Village des Artisans', 'terrain', null, null, 'rare', null, null, null, 'terre', 'village', array['royaume']::text[], null, 'Les Personnages Village gagnent 200 DEF. Une fois par tour, le premier Équipement que tu actives peut cibler un Personnage Village depuis ton Cimetière ; invoque d''abord ce Personnage en Défense, effets annulés, puis équipe-le.', 'vil_013_grand_village_des_artisans', '{}'::jsonb, null, null, true, 133, 1),
    (v_set_id, 'VIL-014', 'Marteau des Trois Métaux', 'relique', null, 'equipment', 'épique', null, null, null, 'feu', 'village', array['royaume']::text[], null, 'Équipe un Personnage Village. Il gagne 300 ATK/DEF pour chaque autre Équipement que tu contrôles, avec un maximum de 900. Si cette carte devrait être détruite, tu peux détruire un autre Équipement que tu contrôles à la place.', 'vil_014_marteau_des_trois_metaux', '{}'::jsonb, null, null, true, 134, 1),
    (v_set_id, 'VIL-015', 'Forge-Ancêtre, Main du Peuple', 'mythique', null, null, 'légendaire', 10, 3600, 3900, 'esprit', 'village', array['ancêtre']::text[], '{"method":"fusion","trigger_card_code":"VIL-010","source":"field","destination":"graveyard","materials":[{"card_code":"VIL-004","quantity":1},{"card_code":"VIL-006","quantity":1},{"kind":"equipment","quantity":1}]}'::jsonb, 'Doit d''abord être invoquée par « Étincelle de la Forge Ancestrale ». À son invocation : équipe-lui jusqu''à 2 Équipements de noms différents depuis ton Cimetière. Une fois par tour : envoie 1 Équipement qu''elle porte au Cimetière ; annule la destruction d''une carte que tu contrôles.', 'vil_015_forge_ancetre_main_du_peuple', '{}'::jsonb, null, null, true, 135, 1),
    (v_set_id, 'MAQ-001', 'Serveur aux Sandales Rapides', 'personnage', null, null, 'commune', 1, 600, 600, 'vent', 'maquis', array['babi']::text[], null, 'À son invocation : tu peux renvoyer 1 autre carte Maquis que tu contrôles dans ta main ; gagne 300 PV.', 'maq_001_serveur_aux_sandales_rapides', '{}'::jsonb, null, null, true, 136, 1),
    (v_set_id, 'MAQ-002', 'Vendeuse d''Alloco Solaire', 'personnage', null, null, 'commune', 2, 900, 1300, 'feu', 'maquis', array['babi']::text[], null, 'Une fois par tour, si tu gagnes des PV : cible 1 Personnage Maquis ; il gagne 300 ATK ce tour.', 'maq_002_vendeuse_d_alloco_solaire', '{}'::jsonb, null, null, true, 137, 1),
    (v_set_id, 'MAQ-003', 'Videur au Grand Sourire', 'personnage', null, null, 'commune', 4, 1800, 2000, 'terre', 'maquis', array['babi']::text[], null, 'Aucun effet.', 'maq_003_videur_au_grand_sourire', '{}'::jsonb, null, null, true, 138, 1),
    (v_set_id, 'MAQ-004', 'DJ du Car Rapide', 'personnage', null, null, 'rare', 4, 1700, 1500, 'vent', 'maquis', array['babi']::text[], null, 'La première fois par tour que tu actives une Action Maquis, cette carte gagne 400 ATK jusqu''à la fin du tour.', 'maq_004_dj_du_car_rapide', '{}'::jsonb, null, null, true, 139, 1),
    (v_set_id, 'MAQ-005', 'Cuisinière de Minuit', 'personnage', null, null, 'rare', 5, 2100, 2300, 'feu', 'maquis', array['village']::text[], null, 'À son invocation : révèle les 3 cartes du dessus de ton deck ; ajoute 1 Action Maquis révélée à ta main et replace les autres sous le deck dans l''ordre de ton choix.', 'maq_005_cuisiniere_de_minuit', '{}'::jsonb, null, null, true, 140, 1),
    (v_set_id, 'MAQ-006', 'Patron du Coin Lumineux', 'personnage', null, null, 'épique', 6, 2500, 2300, 'lumière', 'maquis', array['babi']::text[], null, 'Une fois par tour, après la résolution d''une Action Maquis : gagne 400 PV. Si tu as gagné au moins 800 PV ce tour, pioche 1 carte puis défausse 1 carte.', 'maq_006_patron_du_coin_lumineux', '{}'::jsonb, null, null, true, 141, 1),
    (v_set_id, 'MAQ-007', 'Légende du Quartier Sans Sommeil', 'personnage', null, null, 'épique', 7, 2800, 2600, 'lumière', 'maquis', array['babi']::text[], null, 'Une fois par tour : défausse 1 Action ; cette carte peut effectuer une seconde attaque sur un Personnage ce tour. Les dégâts de combat infligés lors de cette seconde attaque sont divisés par deux, arrondis au supérieur.', 'maq_007_legende_du_quartier_sans_sommeil', '{}'::jsonb, null, null, true, 142, 1),
    (v_set_id, 'MAQ-008', 'Tournée Générale', 'action', 'normal', null, 'commune', null, null, null, 'lumière', 'maquis', '{}'::text[], null, 'Chaque joueur gagne 500 PV. Tu pioches ensuite 1 carte puis défausses 1 carte.', 'maq_008_tournee_generale', '{}'::jsonb, null, null, true, 143, 1),
    (v_set_id, 'MAQ-009', 'Commande Express', 'action', 'quick', null, 'rare', null, null, null, 'vent', 'maquis', array['babi']::text[], null, 'Cible 1 Personnage Maquis ; renvoie-le dans ta main, puis invoque spécialement depuis ta main 1 Personnage Maquis de rang inférieur.', 'maq_009_commande_express', '{}'::jsonb, null, null, true, 144, 1),
    (v_set_id, 'MAQ-010', 'Banquet des Étoiles Urbaines', 'action', 'normal', null, 'épique', null, null, null, 'esprit', 'maquis', array['ancêtre']::text[], null, 'Invocation ancestrale : défausse 2 Actions Maquis de noms différents et sacrifie des Personnages Maquis dont le total des rangs est au moins 8 ; invoque spécialement « Grand Maquisard Cosmique » depuis ta Réserve des Mythiques.', 'maq_010_banquet_des_etoiles_urbaines', '{}'::jsonb, null, null, true, 145, 1),
    (v_set_id, 'MAQ-011', 'Plateau Très Glissant', 'piège', 'normal', null, 'commune', null, null, null, 'eau', 'maquis', array['lagune']::text[], null, 'Lorsqu''un Personnage adverse déclare une attaque : annule l''attaque et renvoie dans ta main 1 Personnage Maquis que tu contrôles.', 'maq_011_plateau_tres_glissant', '{}'::jsonb, null, null, true, 146, 1),
    (v_set_id, 'MAQ-012', 'Addition Contestée', 'piège', 'counter', null, 'rare', null, null, null, 'ombre', 'maquis', array['babi']::text[], null, 'Lorsqu''un effet adverse ferait perdre des PV en dehors du combat : défausse 1 carte ; annule cet effet et gagne 300 PV.', 'maq_012_addition_contestee', '{}'::jsonb, null, null, true, 147, 1),
    (v_set_id, 'MAQ-013', 'Maquis des Mille Saveurs', 'terrain', null, null, 'rare', null, null, null, 'feu', 'maquis', array['babi']::text[], null, 'Les Personnages Maquis gagnent 200 ATK/DEF. Une fois par tour, lorsqu''un joueur gagne des PV par l''effet d''une autre carte, le propriétaire de ce Terrain gagne 200 PV. Ce gain ne peut pas déclencher cet effet.', 'maq_013_maquis_des_mille_saveurs', '{}'::jsonb, null, null, true, 148, 1),
    (v_set_id, 'MAQ-014', 'Marmite Qui Ne Se Vide Jamais', 'relique', null, 'action', 'épique', null, null, null, 'feu', 'maquis', array['village']::text[], null, 'Place cette Relique face visible dans une Zone Action/Piège libre avec 3 marqueurs Portion. Une fois par tour : retire 1 marqueur ; gagne 600 PV. Sans marqueur, envoie cette carte au Cimetière et pioche 1 carte.', 'maq_014_marmite_qui_ne_se_vide_jamais', '{}'::jsonb, null, null, true, 149, 1),
    (v_set_id, 'MAQ-015', 'Grand Maquisard Cosmique', 'mythique', null, null, 'légendaire', 9, 3400, 3100, 'lumière', 'maquis', array['babi']::text[], '{"method":"ancestrale","trigger_card_code":"MAQ-010","requirements":{"all":[{"kind":"action","families":["maquis"],"quantity":2,"distinct_names":true,"source":"hand","payment":"discard"},{"kind":"character","families":["maquis"],"minimum_total_rank":8,"source":"field","payment":"sacrifice"}]}}'::jsonb, 'Doit d''abord être invoqué par « Banquet des Étoiles Urbaines ». À son invocation : gagne 1000 PV, puis ajoute à ta main 1 Action Maquis depuis ton Cimetière. Une fois par tour, après la résolution de ta deuxième Action du tour : détruis 1 carte adverse face visible.', 'maq_015_grand_maquisard_cosmique', '{}'::jsonb, null, null, true, 150, 1)
  on conflict (code) do update set
    set_id = excluded.set_id,
    name = excluded.name,
    category = excluded.category,
    subtype = excluded.subtype,
    relic_mode = excluded.relic_mode,
    rarity = excluded.rarity,
    rank = excluded.rank,
    atk = excluded.atk,
    def = excluded.def,
    attribute = excluded.attribute,
    primary_family = excluded.primary_family,
    secondary_families = excluded.secondary_families,
    mythic_summon_condition = excluded.mythic_summon_condition,
    effect_text = excluded.effect_text,
    effect_key = excluded.effect_key,
    effect_data = excluded.effect_data,
    lore_text = excluded.lore_text,
    art_url = excluded.art_url,
    is_active = excluded.is_active,
    sort_order = excluded.sort_order,
    revision = excluded.revision,
    updated_at = timezone('utc', now());

  insert into public.token_definitions (
    token_key, name, rank, atk, def, attribute, primary_family,
    data, is_active, sort_order
  ) values (
    'sylve', 'Jeton Sylve', 1, 500, 500, 'nature', 'forêt',
    '{"can_be_sacrificed":true,"can_be_set":false,"disappears_when_leaving_field":true}'::jsonb,
    true, 1
  )
  on conflict (token_key) do update set
    name = excluded.name,
    rank = excluded.rank,
    atk = excluded.atk,
    def = excluded.def,
    attribute = excluded.attribute,
    primary_family = excluded.primary_family,
    data = excluded.data,
    is_active = excluded.is_active,
    sort_order = excluded.sort_order,
    updated_at = timezone('utc', now());
end;
$$;

-- Assertions transactionnelles: le seed échoue intégralement si le
-- catalogue ne correspond pas au GDD V2 validé.
do $$
declare
  v_set_id uuid;
  v_total integer;
begin
  select id into v_set_id from public.card_sets where code = 'MCV2-LAUNCH';

  select count(*)::integer into v_total
  from public.cards where set_id = v_set_id;
  if v_total <> 150 then
    raise exception 'Seed V2 invalide: 150 cartes attendues, % trouvées.', v_total;
  end if;

  if (select count(*) from public.cards where is_active) <> 150 then
    raise exception 'Seed V2 invalide: exactement 150 cartes V2 actives sont attendues.';
  end if;

  if exists (
    select expected.category
    from (values
      ('personnage'::text, 70), ('action', 30), ('piège', 20),
      ('terrain', 10), ('relique', 10), ('mythique', 10)
    ) as expected(category, expected_count)
    left join (
      select category, count(*)::integer as actual_count
      from public.cards where set_id = v_set_id group by category
    ) actual using (category)
    where coalesce(actual.actual_count, 0) <> expected.expected_count
  ) then
    raise exception 'Seed V2 invalide: répartition des catégories incorrecte.';
  end if;

  if (select count(distinct primary_family) from public.cards where set_id = v_set_id) <> 10
     or exists (
       select 1 from public.cards where set_id = v_set_id
       group by primary_family having count(*) <> 15
     ) then
    raise exception 'Seed V2 invalide: chaque famille doit contenir 15 cartes.';
  end if;

  if (select count(*) from public.cards where set_id = v_set_id and category = 'mythique') <> 10
     or exists (
       select 1
       from public.cards mythic
       where mythic.set_id = v_set_id
         and mythic.category = 'mythique'
         and not exists (
           select 1 from public.cards trigger_card
           where trigger_card.set_id = v_set_id
             and trigger_card.code = mythic.mythic_summon_condition ->> 'trigger_card_code'
         )
     ) then
    raise exception 'Seed V2 invalide: condition Mythique ou carte déclencheuse absente.';
  end if;

  if exists (
    select 1 from public.cards
    where set_id = v_set_id
      and (
        (category = 'personnage' and rank not between 1 and 8)
        or (category = 'mythique' and rank not between 9 and 10)
        or (category not in ('personnage', 'mythique') and rank is not null)
      )
  ) then
    raise exception 'Seed V2 invalide: rang incompatible avec la catégorie.';
  end if;

  if not exists (
    select 1 from public.token_definitions
    where token_key = 'sylve' and rank = 1 and atk = 500 and def = 500
      and attribute = 'nature' and primary_family = 'forêt' and is_active
  ) then
    raise exception 'Seed V2 invalide: définition du Jeton Sylve absente.';
  end if;
end;
$$;
